title: E-Sk8FR Wiki
description: Wiki communautaire français sur le skateboard électrique - Guides, tutoriels et ressources
theme: just-the-docs

url: https://e-sk8fr.github.io

logo: "/assets/images/logo.png"

aux_links:
  GitHub: https://github.com/Pixnop/E-sk8FR-Wiki
  Forum E-Sk8FR: https://www.e-sk8.fr
  Discord: https://discord.gg/4g9rtnGj5m

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true

color_scheme: esk8fr

back_to_top: true
back_to_top_text: "Retour en haut"

last_edit_timestamp: true
last_edit_time_format: "%d %b %Y à %H:%M"

gh_edit_link: true
gh_edit_link_text: "Modifier cette page sur GitHub"
gh_edit_repository: "https://github.com/Pixnop/E-sk8FR-Wiki"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

lang: fr-FR
